version: '3'
services:

  rabbitmq:
    image: rabbitmq:3-alpine
    container_name: patrowlmanager-rabbitmq
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error}]
    expose:
      - '5672'

  db:
    image: postgres:11-alpine
    restart: always
    container_name: patrowlmanager-postgres
    environment:
      - POSTGRES_DB=patrowl_db
      - POSTGRES_USER=SECUREFLOW_DB_USER
      - POSTGRES_PASSWORD=SECUREFLOW_DB_PASSWD_TO_CHANGE
    expose:
      - '5432'
    volumes:
      - ./var/db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    #   - ./pg_data:/var/lib/postgresql/data/

  web:
    container_name: patrowlmanager-django
    build: .
    image: khulnasoft/secureflow-manager-community-edition:${SECUREFLOW_MANAGER_VERSION}
    environment:
      - POSTGRES_HOST=db
      - DEBUG=True
      - RABBITMQ_HOSTNAME=rabbitmq:5672
    depends_on:
      - db
      - rabbitmq
    expose:
      - "8003"
    volumes:
      - ./staticfiles:/opt/secureflow-manager/staticfiles
      - ./media:/opt/secureflow-manager/media
    links:
      - db
      - rabbitmq

  nginx:
    image: nginx:stable-alpine
    container_name: patrowlmanager-nginx
    ports:
      - "8083:8083"
    volumes:
      - ./staticfiles:/opt/secureflow-manager/staticfiles
      # - ./media:/opt/secureflow-manager/media
      - ./var/log:/opt/secureflow-manager/var/log
      - ./nginx_docker.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
